[Settings]
ID = "reactive-react"

# for more: https://www.netlify.com/docs/netlify-toml-reference/

[build]
  # This is the directory to change to before starting a build.
  # base    = "project/"
  # NOTE: This is where we will look for package.json/.nvmrc/etc, not root.
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "demos/dist/"
  # This will be your default build command
  command = "yarn demo:build"
  # This is where we will look for your lambda functions
  # functions = "project/functions/"